services:
  - type: web
    name: startup-apply
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_EMAILJS_SERVICE_ID
        value: service_gl3xzva
      - key: VITE_EMAILJS_TEMPLATE_ID
        value: template_h62tu28
      - key: VITE_EMAILJS_PUBLIC_KEY
        value: 12DTBz2EjgKE1P3Ef
      - key: VITE_API_URL
        value: https://startup-apply-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  
  # Simple API for storing applications
  - type: web
    name: startup-apply-api
    env: node
    buildCommand: cd api && npm install
    startCommand: cd api && node server.js
    envVars:
      - key: DATA_DIR
        value: /data
      - key: BASE_URL
        value: https://startup-apply-api.onrender.com 
    disk:
      name: startup-data
      mountPath: /data
      sizeGB: 1 